BookListRazorPages/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Context.DbObjects;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repos;

namespace BookListRazorPages.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class BookController : Controller
    {
        private readonly IRepository<Book> repository;

        public BookController(IRepository<Book> repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var books = await this.repository.GetAll();
            return Ok(new
            {
                data = books
            });
        }


        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var book = await this.repository.GetById(id);
            if (book == null)
            {
                return Ok(new
                {
                    success = false,
                    message = "Error while deleting !!"
                });
            }
            else
            {
                await this.repository.Remove(book);
                return Ok(new
                {
                    success = true,
                    message = "Deleted successfully"
                });
            }
        }
    }
}

BookListRazorPages/Pages/BookList/Create.cshtml.cs
using Context.DbObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repos;
using System.Threading.Tasks;

namespace BookListRazorPages.Pages.BookList
{
    public class CreateModel : PageModel
    {
        private readonly IRepository<Book> repository;

        [BindProperty]
        public Book Book { get; set; }

        public CreateModel(IRepository<Book> repository)
        {
            this.repository = repository;
        }

        public void OnGet()
        {

        }

        public async Task<ActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await this.repository.Add(Book);
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

BookListRazorPages/Pages/BookList/Edit.cshtml.cs
using Context.DbObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repos;
using System.Threading.Tasks;

namespace BookListRazorPages.Pages.BookList
{
    public class EditModel : PageModel
    {
        private readonly IRepository<Book> repository;

        [BindProperty]
        public Book Book { get; set; }
        public EditModel(IRepository<Book> repository)
        {
            this.repository = repository;
        }

        public async Task OnGet(int id)
        {
            Book = await this.repository.GetById(id);
        }

        public async Task<ActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await this.repository.Update(Book);
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

BookListRazorPages/Pages/BookList/Index.cshtml.cs
using Context.DbObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repos;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BookListRazorPages.Pages.BookList
{
    public class IndexModel : PageModel
    {
        private readonly IRepository<Book> repository;
        public IEnumerable<Book> Books { get; set; }
        public IndexModel(IRepository<Book> repository)
        {
            this.repository = repository;
        }

        public async Task OnGet()
        {
            Books = await repository.GetAll();
        }

        public async Task<ActionResult> OnPostRemove(int id)
        {
            var book = await this.repository.GetById(id);
            if (book != null)
            {
                await this.repository.Remove(book);
                return RedirectToPage("Index");
            }
            else
            {
                return NotFound();
            }
        }
    }
}

BookListRazorPages/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BookListRazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BookListRazorPages/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BookListRazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

BookListRazorPages/Pages/BookList/Create.cshtml
@page
@model BookListRazorPages.Pages.BookList.CreateModel
@{
    ViewData["Title"] = "Create";
}

    <br />
    <h2 class="text-info">Create New Book</h2>
    <br />

    <div class="border container p-3">
        <form method="post">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Book.Name"></label>
                </div>
                <div class="col-6">
                    <input asp-for="Book.Name" class="form-control" />
                    <span class="text-danger" asp-validation-for="Book.Name"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Book.Author"></label>
                </div>
                <div class="col-6">
                    <input asp-for="Book.Author" class="form-control" />
                    <span class="text-danger" asp-validation-for="Book.Author"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-3 offset-4">
                    <input type="submit" name="submit" value="Create" class="btn btn-primary form-control" />
                </div>
                <div class="col-3">
                    <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
                </div>
            </div>
        </form>
    </div>

@section Scripts{
    <partial name="_ValidationScriptsPartial">
 }

BookListRazorPages/Pages/BookList/Edit.cshtml
@page
@model BookListRazorPages.Pages.BookList.EditModel
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2 class="text-info">Edit Book</h2>
<br />

<div class="border container p-3">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="Book.Id" />
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.Name"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Author"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Author" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.Author"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3 offset-4">
                <input type="submit" name="submit" value="Save" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial">
}

BookListRazorPages/Pages/BookList/Index.cshtml
@page
@model BookListRazorPages.Pages.BookList.IndexModel
@{
    ViewData["Title"] = "BookList";
}

<br />
<div class="container row p-0 m-0 ">
    <div class="col-9">
        <h2 class="text-info">Book List</h2>
    </div>
    <div class="col-3">
        <a asp-page="Create" class="btn btn-success form-control">Create New Book</a>
    </div>
</div>

<div class="col-12 p-3 m-3">
    @if (Model.Books.Count() > 0)
    {
        <table class="table table-striped border table-bordered">
            <thead>
                <tr class="table-secondary">
                    <th style="width:35%">
                        <label asp-for="@Model.Books.FirstOrDefault().Name"></label>
                    </th>
                    <th style="width:35%">
                        <label asp-for="@Model.Books.FirstOrDefault().Author"></label>
                    </th>
                    <th style="width:30%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var book in Model.Books)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(x => book.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(x => book.Author)
                        </td>
                        <td class="d-flex">
                            <a asp-page="Edit" asp-route-id="@book.Id" class="btn btn-info btn-sm text-white">Edit</a>
                            <form method="post">
                                <button asp-page-handler="Remove" asp-route-id="@book.Id" OnClick="return confirm('Are you sure you want to delete this book ?!!')" class="btn btn-danger btn-sm ml-1">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Books Available !!</p>
    }
</div>


<div class="col-12" style="text-align:center;">
    <br />
    <span class="h3 text-info">OR</span>
    <br />
    <br />
</div>
<div class="col-12 border p-3">
    <table id="book-table" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{ 
    <script src="~/js/bookList.js"></script>
}

BookListRazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookListRazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookListRazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BookListRazorPages</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/BookList/Index">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BookListRazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>